osx_image: xcode7.3
language: objective-c

script:
- xcodebuild clean build -project Pages.xcodeproj -scheme "Pages-iOS" -sdk iphonesimulator
- xcodebuild test -project Pages.xcodeproj -scheme "Pages-iOS" -sdk iphonesimulator
